# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
name: Ujjwal Sharma | PhD Student @ University of Amsterdam
email: u.sharma@uva.nl
description: > # this means to ignore newlines until "url:"
  Ujjwal Sharma. PhD candidate. Amsterdam Business School and University of Amsterdam. I am a second-year PhD student working on Machine Learning for Marketing at the University of Amsterdam, advised by Prof. Willemijn van Dolen and Dr. Stevan Rudinac.
footer_text: >
    Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a>

url:  # the base hostname & protocol for your site
baseurl: # the subpath of your site, e.g. /blog/
last_updated: # leave blank if you don't want to display last updated

# -----------------------------------------------------------------------------
# Open Graph
# -----------------------------------------------------------------------------
# Display links to the page with a preview object on social media.
# To achieve this, change serve_og_meta to true and then provide the URL of the
# preview image as the value of og_image.
serve_og_meta: false # Include Open Graph meta tags in the HTML head
og_image: # The site-wide (default for all links) Open Graph preview image
# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: ujjwalx
twitter_username: #ujjwalsharmax
linkedin_username: ujjwal-sharma-a36133ba
scholar_userid: # your Google Scholar ID
orcid_id: #0000-0003-0285-1303
medium_username: # your Medium username
quora_username: # your Quora username
publons_id: # your ID on Publons
research_gate_profile: # your profile on ResearchGate
blogger_url: # your blogger URL

contact_note: >
  E-mail is the fastest way to reach me.

google_analytics: # out your google-analytics code

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: Interesting Snippets from my Research
blog_description:  

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

text:
  pagination:
    newer: 'Newer'
    older: 'Older'

# Comments
disqus_shortname: # put your disqus shortname

# Optional features
show_social_icons:  false
enable_anchorjs:    false
enable_katex:       true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

news_limit: 5

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: pygments

# Includes & excludes
include: ['_pages']
exclude: [vendor]

# Plug-ins
plugins:
    - jekyll-email-protect
    - jekyll-paginate
    - jekyll/scholar
    - jemoji
    - jekyll-sitemap
    - jekyll-seo-tag

# Jekyll-Scholar
scholar:

  last_name: Sharma
  style: apa
  locale: en

  sort_by: year
  order: descending

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.9.0"
anchorjs_version: "3.2.2"
