--- # -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# Site settings
title: Ujjwal Sharma
first_name: Ujjwal
last_name: Sharma
email: u.sharma@uva.nl
description: > # this means to ignore newlines until "url:"
  Ujjwal Sharma. PhD candidate. Amsterdam Business School and University of Amsterdam. I am a second-year PhD student working on Machine Learning for Marketing at the University of Amsterdam, advised by Prof. Willemijn van Dolen and Dr. Stevan Rudinac.
footer_text: >
  Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a>


url: https://www.ujjwalsharma.net
baseurl: # the subpath of your site, e.g. /blog/
last_updated: # leave blank if you don't want to display last updated

navbar_fixed: true
footer_fixed: true

# Dimensions
max_width: 900px

# TODO: add layout settings (single page vs. multi-page)

# -----------------------------------------------------------------------------
# Open Graph
# -----------------------------------------------------------------------------
# Display links to the page with a preview object on social media.
serve_og_meta: false # Include Open Graph meta tags in the HTML head
og_image: # The site-wide (default for all links) Open Graph preview image

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: ujjwalx
twitter_username: #ujjwalsharmax
linkedin_username: ujjwal-sharma-a36133ba
# scholar_userid: # your Google Scholar ID
orcid_id: 0000-0003-0285-1303
# medium_username: # your Medium username
# quora_username: # your Quora username
# publons_id: # your ID on Publons
# research_gate_profile: # your profile on ResearchGate
# blogger_url: # your blogger URL
# work_url: # work page URL
# keybase_username: # your keybase user name
# wikidata_id: # your wikidata id

contact_note: >
  Email is the fastest way to reach me.

google_analytics: UA-137531322-2

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------

blog_name: Interesting Snippets from my Research
blog_description: 

# Pagination
pagination:
  enabled: true

# Comments
disqus_shortname: # put your disqus shortname

# Optional features
show_social_icons: false
enable_anchorjs: false
enable_katex: false

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

news_limit: 5

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Markdown and syntax highlight
markdown: kramdown
highlighter: rouge
highlight_theme: github  # https://github.com/jwarby/jekyll-pygments-themes
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# Includes & excludes
include: ['_pages']
exclude:
  - bin
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
keep_files:
  - CNAME
  - .nojekyll
  - .git

# Plug-ins
plugins:
  - jekyll-email-protect
  - jekyll-paginate
  - jekyll/scholar
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-paginate-v2
  - jekyll-twitter-plugin

# -----------------------------------------------------------------------------
# Jekyll Scholar
# -----------------------------------------------------------------------------

scholar:
  last_name: Sharma
  first_name: [Ujjwal, U.]
  
  style: apa
  locale: en

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------

enable_google_analytics:    false
enable_panelbear_analytics: false
enable_mansory:             true
enable_math:                true
enable_tooltips:            false
enable_darkmode:            true
show_social_icons:          false

# -----------------------------------------------------------------------------
# Library versions
# -----------------------------------------------------------------------------

academicons:
  version: "1.9.0"
  integrity: "sha512-W4yqoT1+8NLkinBLBZko+dFB2ZbHsYLDdr50VElllRcNt2Q4/GSs6u71UHKxB7S6JEMCp5Ve4xjh3eGQl/HRvg=="
bootstrap:
  version: "4.5.2"
  integrity:
    css: "sha512-MoRNloxbStBcD8z3M/2BmnT+rg4IsMxPkXaGh2zD6LGNNFE80W3onsAhRcMAMrSoyWL9xD7Ert0men7vR8LUZg=="
    js: "sha512-M5KW3ztuIICmVIhjSqXe01oV2bpe248gOxqmlcYrEzAvws7Pw3z6BK0iGbrwvdrUQUhi3eXgtxp5I8PDo9YfjQ=="
fontawesome:
  version: "5.14.0"
  integrity: "sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog=="
jquery:
  version: "3.5.1"
  integrity: "sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
mathjax:
  version: "3.1.2"
mansory:
  version: "4.2.2"
  integrity: "sha256-Nn1q/fx0H7SNLZMQ5Hw5JLaTRZp0yILA/FRexe19VdI="
mdb:
  version: "4.19.1"
  integrity:
    css: "sha512-RO38pBRxYH3SoOprtPTD86JFOclM51/XTIdEPh5j8sj4tp8jmQIx26twG52UaLi//hQldfrh7e51WzP9wuP32Q=="
    js: "sha512-Mug9KHKmroQFMLm93zGrjhibM2z2Obg9l6qFG2qKjXEXkMp/VDkI4uju9m4QKPjWSwQ6O2qzZEnJDEeCw0Blcw=="
popper:
  version: "2.4.4"
  integrity: "sha512-eUQ9hGdLjBjY3F41CScH3UX+4JDSI9zXeroz7hJ+RteoCaY+GP/LDoM8AO+Pt+DRFw3nXqsjh9Zsts8hnYv8/A=="
