[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "no-referrer"
X-Content-Type-Options = "nosniff"

[[plugins]]
package = "netlify-plugin-inline-source"

# All inputs are optional, so you can omit this section.
# Defaults are shown below.
# You can also refer to the `inline-source` documentation: https://github.com/popeindustries/inline-source#usage.
[plugins.inputs]
# Attribute used to parse sources. All tags will be parsed if set to `false`.
attribute = "inline"
# Enable/disable compression of inlined content.
compress = true
# Maintain leading whitespace when `compress` is `false`.
pretty = false
# Disable inlining based on tag, type, and/or format.
ignore = []
# Convert `<img inline src="*.svg" />` to `<img>` and not `<svg>`.
svgAsImage = false

# [[plugins]]
# package = "netlify-plugin-subfont"

# [plugins.inputs]
# # An array of glob patterns for pages on your site
# # Recursive traversal will start from these
# entryPoints = ["*.html"]
# # Follow your links across all pages to optimize the fonts across the antire site
# recursive = true
# # Subfont lets you set CSS font-display value of the optimized subsets
# # See https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display
# fontDisplay = "swap"
# # Inline generated CSS @font-face blocks into each page
# # When set to `false` an external CSS file will be created
# inlineCss = false
# # Inline generated font subsets into their respective @font-face blocks
# # When set to `false` external font files will be created
# inlineFonts = false
